version: "1.5"
trigger:
  branches:
    - main
  event:
    - push
    - pull_request
stages:
  - name: 发布到预览知识库
    jobs:
      - name: 发布到预览知识库
        component: git-to-yuque
        inputs:
          # 预览知识库的命名空间， 【这里按需调整】
          yuqueNamespace: eg6z1a/qpbul9
          yuqueSite: https://mosn-layotto.yuque.com/
